
# AT command strings
RESET_COMMAND = "AT Z"
ECHO_OFF_COMMAND = "AT E0"
ECHO_ON_COMMAND = "AT E1"
BATTERY_VOLTAGE_COMMAND = "AT RV"
SET_PROTOCOL_AUTO_COMMAND = "AT SP 0"
DESCRIBE_PROTOCOL_COMMAND = "AT DP"

# TODO: externalize configuration settings
DEFAULT_BAUDRATE = 38400
DEFAULT_BYTESIZE = 8
DEFAULT_PORTNAME = '/dev/rfcomm0'
DEFAULT_STOPBITS = 1
DEFAULT_TIMEOUT = 3

DEFAULT_RETRIES = 10
