# AT command strings
RESET_COMMAND = "AT Z"
ECHO_OFF_COMMAND = "AT E0"
ECHO_ON_COMMAND = "AT E1"
BATTERY_VOLTAGE_COMMAND = "AT RV"
SET_PROTOCOL_AUTO_COMMAND = "AT SP 0"
DESCRIBE_PROTOCOL_COMMAND = "AT DP"

DEFAULT_RETRIES = 10
