# AT command strings
RESET_COMMAND = "ATZ"
ECHO_OFF_COMMAND = "ATE0"
ECHO_ON_COMMAND = "ATE1"
BATTERY_VOLTAGE_COMMAND = "ATRV"
SET_PROTOCOL_AUTO_COMMAND = "ATSPA3"
DESCRIBE_PROTOCOL_COMMAND = "ATDPN"

DEFAULT_RETRIES = 10
NO_RESULT = "NODATA"
